### ISSUE TITLE
Not the same Font as in the Screenshot

### ISSUE THREAD

**Issue by handkerchief333** [jontaydev/monokai-pro-jetbrains#3]
Hi there. 
Great Work! Thank you very much. I have installed the plugin.
PhpStorm 2020.1
Windows 10

The color scheme seems to be legit, but the fonts are different to the screenshot of your project. Is there a difference with the OS or am I missing something?

Thank you very much for helping me.

![image](https://user-images.githubusercontent.com/41755733/79571694-ebb57980-80bb-11ea-8bb2-260ad8be8d9a.png)

**Comment by jontaydev** [comment]
The font used in the screenshots is Operator Mono, a paid font: https://www.typography.com/fonts/operator

I can't bundle a font in the plugin, but I can set the default font to use from your system: https://github.com/jontaydev/monokai-pro-jetbrains/blob/master/resources/themes/Monokai%20Pro.xml#L37

This color scheme was forked from the popular Material plugin, and I left the default font as Menlo. But with the recent release of JetBrains Mono, I may switch to that.

But your right, the screenshots are a bit deceiving since they are not using the default font. Maybe when I update the default font, I will also update the screenshots as well. Sorry for the confusion.

**Comment by jontaydev** [comment]
By the way, if your looking for a similar font that's free, check out [Dank Mono](https://dank.sh), and [Fira Code](https://github.com/tonsky/FiraCode).

**Comment by handkerchief333** [comment]
Thank you very much for your great and fast support.
Now it's clear to me. 

May I ask you if it is also possible to match the same colors like the original theme? Or is there a technical or copyright reason behind this? Because instead of pink/red, the original theme use a very beautiful blue or cyan color as main highlighted color for e.g. function, if/else or class words.
https://monokai.pro/vscode

Thank you again.

**Comment by jontaydev** [comment]
Keep in mind, this plugin has 5 themes bundled in:

- Monokai Pro
- Monokai Pro (Filter Octagon)
- Monokai Pro (Filter Ristretto)
- Monokai Pro (Filter Spectrum)
- Monokai Pro (Filter Machine)

When you install the Monokai Pro plugin, I think it defaults to loading the Filter Spectrum theme. (I need to fix that, the default should be Monokai Pro with no filter). Try switching to Monokai Pro without filter, and see if that looks like what you wanted. 

The colors should match exactly with the official colors from [https://monokai.pro](https://monokai.pro). However, JetBrains and VSCode will probably put the colors in different places, because of how they parse the syntax differently.

**Comment by handkerchief333** [comment]
I changed the themes, but the only thing that changes between these themes is the background color, but not the font/sign colors. They are all the same, regardless which theme i choose.

![image](https://user-images.githubusercontent.com/41755733/79583580-93877300-80cd-11ea-9a4b-616737a4393f.png)

![image](https://user-images.githubusercontent.com/41755733/79583659-a8640680-80cd-11ea-9e06-a2be905e89b1.png)

So I asume that's not a correct function of the themes? 
Is it possible that there are problems with the version 2020.1 or maybe some individual settings (before I installed your theme) in my phpstorm?

**Comment by jontaydev** [comment]
The text colors do change, but very subtly. If you look at https://monokai.pro, and click back/forth between the filter examples on the website, you will see the text colors barely change.

Also keep in mind when switching themes, you have to change both the Ul theme (from Appearance and Behavior), and also the color scheme (from Color Scheme Font). Maybe you have them mismatched?

**Comment by handkerchief333** [comment]
Ok I see. And I was wrong with my last paragraph. Now I can setting this up how I like it, thanks again. You are the fastest responser on Github :)

PS: One last tip for a better usabilty. If you are hovering menus and submenus, there are no highlights, so it's not easy to see where you are with your mouse. It would be great if there is for example a yellow font hover effect.

**Comment by jontaydev** [comment]
Yea, I think your referring to this issue that I need to work on: https://github.com/jontaydev/monokai-pro-jetbrains/issues/2
